[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
nerve_sides = "DzhHCeBfB66VCTdeiVCfYM9DuE9pNmsHeFLpUdWEbpFD"

[programs.devnet]
nerve_sides = "DzhHCeBfB66VCTdeiVCfYM9DuE9pNmsHeFLpUdWEbpFD"

[provider]
cluster = "localnet"
wallet = "keys/devnet-operator.json"

